<?php

namespace Database\Seeders;

use App\Models\Allergen;
use App\Models\Ingredient;
use App\Models\IngredientCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            // Céréales & farines
            ['name' => 'Farine de blé', 'unit' => 'kg', 'price' => 1.20, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de blé complète', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de seigle', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de sarrasin', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de maïs', 'unit' => 'kg', 'price' => 1.90, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de riz', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de châtaigne', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Semoule de blé', 'unit' => 'kg', 'price' => 1.60, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Riz basmati', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Riz rond', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Riz complet', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Pâtes (spaghetti)', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Pâtes (penne)', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Couscous', 'unit' => 'kg', 'price' => 1.90, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Quinoa', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Boulgour', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Polenta', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => "Flocons d'avoine", 'unit' => 'kg', 'price' => 2.30, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Levure boulangère', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Levure chimique', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Bicarbonate de soude', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Chapelure', 'unit' => 'kg', 'price' => 2.10, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Fécule de maïs', 'unit' => 'kg', 'price' => 2.40, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Pain de mie', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Céréales & farines', 'allergens' => ['gluten', 'lait']],
            ['name' => 'Baguette de pain', 'unit' => 'pièce', 'price' => 1.10, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],

            // Produits laitiers
            ['name' => 'Beurre', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Beurre doux', 'unit' => 'kg', 'price' => 6.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème fraîche épaisse', 'unit' => 'L', 'price' => 3.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème liquide entière', 'unit' => 'L', 'price' => 3.20, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait entier', 'unit' => 'L', 'price' => 1.10, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait demi-écrémé', 'unit' => 'L', 'price' => 1.05, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait écrémé', 'unit' => 'L', 'price' => 1.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait concentré non sucré', 'unit' => 'L', 'price' => 2.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Yaourt nature', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Fromage blanc', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Mascarpone', 'unit' => 'kg', 'price' => 7.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Ricotta', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Gruyère râpé', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Emmental râpé', 'unit' => 'kg', 'price' => 10.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Parmesan', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Mozzarella', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Chèvre frais', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Comté', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Camembert', 'unit' => 'pièce', 'price' => 3.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Roquefort', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Feta', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème épaisse allégée', 'unit' => 'L', 'price' => 3.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Babeurre', 'unit' => 'L', 'price' => 1.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Petit-suisse', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Beurre clarifié (ghee)', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],

            // Œufs
            ['name' => 'Oeufs', 'unit' => 'pièce', 'price' => 0.30, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Oeufs de caille', 'unit' => 'pièce', 'price' => 0.25, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ["name" => "Blancs d'oeufs liquides", 'unit' => 'L', 'price' => 4.00, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ["name" => "Jaunes d'oeufs liquides", 'unit' => 'L', 'price' => 5.50, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Oeufs durs', 'unit' => 'pièce', 'price' => 0.40, 'category' => 'Œufs', 'allergens' => ['oeuf']],

            // Fruits secs & oléagineux
            ['name' => 'Amandes effilées', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Amandes entières', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Amandes en poudre', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Noisettes', 'unit' => 'kg', 'price' => 13.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Noix', 'unit' => 'kg', 'price' => 12.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Noix de cajou', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Pistaches', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Pignons de pin', 'unit' => 'kg', 'price' => 35.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits coque']],
            ['name' => 'Cacahuètes', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Beurre de cacahuète', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de tournesol', 'unit' => 'kg', 'price' => 5.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de courge', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de sésame', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de lin', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de chia', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Raisins secs', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Abricots secs', 'unit' => 'kg', 'price' => 7.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Dattes', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Figues sèches', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Noix de coco râpée', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],

            // Poissons & fruits de mer
            ['name' => 'Saumon', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Cabillaud', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Thon frais', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Thon en boîte', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Truite', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Bar (loup)', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Dorade', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Sole', 'unit' => 'kg', 'price' => 28.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Merlan', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Colin (lieu noir)', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Sardine', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Maquereau', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Anchois', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Hareng', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Flétan', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Anguille', 'unit' => 'kg', 'price' => 24.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Crevettes', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Gambas', 'unit' => 'kg', 'price' => 26.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Langoustines', 'unit' => 'kg', 'price' => 32.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Homard', 'unit' => 'kg', 'price' => 45.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Crabe', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Moules', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Huîtres', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Coquilles Saint-Jacques', 'unit' => 'kg', 'price' => 30.00, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Calamars', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Poissons & fruits de mer', 'allergens' => []],

            // Viandes
            ['name' => 'Boeuf haché', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Entrecôte de boeuf', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bavette de boeuf', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rôti de boeuf', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Paleron de boeuf (bourguignon)', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Filet de boeuf', 'unit' => 'kg', 'price' => 32.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Joue de boeuf', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Escalope de veau', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Blanquette de veau', 'unit' => 'kg', 'price' => 17.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rôti de veau', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Filet mignon de porc', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Côtes de porc', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Échine de porc', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Lardons', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Jambon blanc', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Jambon sec', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Saucisses de Toulouse', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Chorizo', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Saucisson sec', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bacon', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Pancetta', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rillettes', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Boudin noir', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Viandes', 'allergens' => []],
            ["name" => "Gigot d'agneau", 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ["name" => "Côtelettes d'agneau", 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ["name" => "Épaule d'agneau", 'unit' => 'kg', 'price' => 15.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Poulet entier', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Blanc de poulet', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Cuisse de poulet', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Escalope de dinde', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Magret de canard', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Confit de canard', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Foie gras', 'unit' => 'kg', 'price' => 55.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Lapin', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Caille', 'unit' => 'pièce', 'price' => 4.50, 'category' => 'Viandes', 'allergens' => []],

            // Légumes
            ['name' => 'Céleri branche', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Légumes', 'allergens' => ['celeri']],
            ['name' => 'Céleri-rave', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => ['celeri']],
            ['name' => 'Pomme de terre', 'unit' => 'kg', 'price' => 1.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Carotte', 'unit' => 'kg', 'price' => 1.10, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Oignon', 'unit' => 'kg', 'price' => 1.30, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Échalote', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Ail', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poireau', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Tomate', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Concombre', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Courgette', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Aubergine', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poivron rouge', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poivron vert', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Champignon de Paris', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Cèpes', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou blanc', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou-fleur', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Brocoli', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou rouge', 'unit' => 'kg', 'price' => 1.70, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou de Bruxelles', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Épinard', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Salade verte', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Roquette', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Mâche', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Endive', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Betterave', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Navet', 'unit' => 'kg', 'price' => 1.60, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Radis', 'unit' => 'botte', 'price' => 1.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Petit pois', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Haricot vert', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Fève', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Asperge verte', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Artichaut', 'unit' => 'pièce', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Fenouil', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Courge butternut', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Potiron', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Maïs doux', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Oignon grelot', 'unit' => 'kg', 'price' => 3.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Ciboulette', 'unit' => 'botte', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Persil', 'unit' => 'botte', 'price' => 1.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Basilic', 'unit' => 'botte', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Coriandre fraîche', 'unit' => 'botte', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Piment fort', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Gingembre frais', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Légumes', 'allergens' => []],

            // Fruits
            ['name' => 'Pomme', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Poire', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Banane', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Orange', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Citron', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Citron vert', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pamplemousse', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mandarine', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Ananas', 'unit' => 'pièce', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mangue', 'unit' => 'pièce', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Kiwi', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Fraise', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Framboise', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Myrtille', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mûre', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Cerise', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Abricot', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pêche', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Nectarine', 'unit' => 'kg', 'price' => 3.60, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Prune', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Raisin blanc', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Raisin noir', 'unit' => 'kg', 'price' => 4.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Melon', 'unit' => 'pièce', 'price' => 2.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pastèque', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Grenade', 'unit' => 'pièce', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Figue fraîche', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Litchi', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Papaye', 'unit' => 'pièce', 'price' => 3.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Fruit de la passion', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Rhubarbe', 'unit' => 'kg', 'price' => 3.80, 'category' => 'Fruits', 'allergens' => []],

            // Condiments & épices
            ['name' => 'Moutarde de Dijon', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Condiments & épices', 'allergens' => ['moutarde']],
            ['name' => 'Sauce soja', 'unit' => 'L', 'price' => 3.20, 'category' => 'Condiments & épices', 'allergens' => ['soja']],
            ['name' => 'Sel fin', 'unit' => 'kg', 'price' => 0.80, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre noir', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre blanc', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Paprika', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Curcuma', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cumin', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cannelle', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Muscade', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Curry', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ["name" => "Piment d'Espelette", 'unit' => 'kg', 'price' => 30.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Herbes de Provence', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Laurier', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Thym', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Romarin', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Origan', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vanille (gousse)', 'unit' => 'pièce', 'price' => 3.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ["name" => "Huile d'olive", 'unit' => 'L', 'price' => 7.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile de tournesol', 'unit' => 'L', 'price' => 2.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile de colza', 'unit' => 'L', 'price' => 3.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre balsamique', 'unit' => 'L', 'price' => 6.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre de cidre', 'unit' => 'L', 'price' => 3.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Ketchup', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Mayonnaise', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Condiments & épices', 'allergens' => ['oeuf']],
            ['name' => 'Sauce Worcestershire', 'unit' => 'L', 'price' => 8.00, 'category' => 'Condiments & épices', 'allergens' => ['poisson']],
            ['name' => 'Miel', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sucre blanc', 'unit' => 'kg', 'price' => 1.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sucre roux', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cassonade', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Condiments & épices', 'allergens' => []],

            // Boissons & vins
            ['name' => 'Vin blanc', 'unit' => 'L', 'price' => 5.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Vin rouge', 'unit' => 'L', 'price' => 5.50, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Vin rosé', 'unit' => 'L', 'price' => 5.20, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Champagne', 'unit' => 'L', 'price' => 25.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Porto', 'unit' => 'L', 'price' => 12.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Cognac', 'unit' => 'L', 'price' => 30.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Rhum brun', 'unit' => 'L', 'price' => 18.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Bière blonde', 'unit' => 'L', 'price' => 2.50, 'category' => 'Boissons & vins', 'allergens' => ['gluten']],
            ['name' => 'Cidre brut', 'unit' => 'L', 'price' => 3.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Jus de pomme', 'unit' => 'L', 'price' => 2.20, 'category' => 'Boissons & vins', 'allergens' => []],
        ];

        foreach ($ingredients as $data) {
            $categoryId = IngredientCategory::where('slug', Str::slug($data['category']))->value('id');

            $ingredient = Ingredient::firstOrCreate(
                ['slug' => Str::slug($data['name'])],
                [
                    'name' => $data['name'],
                    'unit' => $data['unit'],
                    'price' => $data['price'],
                    'ingredient_category_id' => $categoryId,
                ]
            );

            $ingredient->update(['ingredient_category_id' => $categoryId]);

            $allergenIds = Allergen::whereIn('slug', array_map(fn ($name) => Str::slug($name), $data['allergens']))
                ->pluck('id');

            $ingredient->allergens()->sync($allergenIds);
        }
    }
}
