<?php

namespace Database\Seeders;

use App\Models\Allergen;
use App\Models\Ingredient;
use App\Models\IngredientCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            // Céréales & farines
            ['name' => 'Baguette de pain', 'slug' => 'baguette-de-pain', 'unit' => 'pièce', 'price' => 1.10, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Bicarbonate de soude', 'slug' => 'bicarbonate-de-soude', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Biscuits boudoirs (paquet)', 'slug' => 'biscuits-boudoirs-paquet', 'unit' => 'paquet', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => ['gluten', 'lait', 'oeuf']],
            ['name' => 'Boulgour', 'slug' => 'boulgour', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Chapelure', 'slug' => 'chapelure', 'unit' => 'kg', 'price' => 2.10, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Chapelure panko', 'slug' => 'chapelure-panko', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Couscous', 'slug' => 'couscous', 'unit' => 'kg', 'price' => 1.90, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de blé', 'slug' => 'farine-de-ble', 'unit' => 'kg', 'price' => 1.20, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de blé complète', 'slug' => 'farine-de-ble-complete', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Farine de châtaigne', 'slug' => 'farine-de-chataigne', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de maïs', 'slug' => 'farine-de-mais', 'unit' => 'kg', 'price' => 1.90, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de riz', 'slug' => 'farine-de-riz', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de sarrasin', 'slug' => 'farine-de-sarrasin', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Farine de seigle', 'slug' => 'farine-de-seigle', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Fécule de maïs', 'slug' => 'fecule-de-mais', 'unit' => 'kg', 'price' => 2.40, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Feuilles de brick', 'slug' => 'feuilles-de-brick', 'unit' => 'pièce', 'price' => 0.35, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Flocons d\'avoine', 'slug' => 'flocons-davoine', 'unit' => 'kg', 'price' => 2.30, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Gnocchetti sardi (malloreddus)', 'slug' => 'gnocchetti-sardi-malloreddus', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Levure boulangère', 'slug' => 'levure-boulangere', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Levure chimique', 'slug' => 'levure-chimique', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Nouilles de riz plates (séchées)', 'slug' => 'nouilles-de-riz-plates', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Pain à burger', 'slug' => 'pain-a-burger', 'unit' => 'pièce', 'price' => null, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Pain de mie', 'slug' => 'pain-de-mie', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Céréales & farines', 'allergens' => ['gluten', 'lait']],
            ['name' => 'Pâtes (penne)', 'slug' => 'pates-penne', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Pâtes (spaghetti)', 'slug' => 'pates-spaghetti', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Pâtes à lasagne (feuilles)', 'slug' => 'pates-a-lasagne-feuilles', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Polenta', 'slug' => 'polenta', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Quinoa', 'slug' => 'quinoa', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Riz basmati', 'slug' => 'riz-basmati', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Riz complet', 'slug' => 'riz-complet', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Riz rond', 'slug' => 'riz-rond', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Semoule de blé', 'slug' => 'semoule-de-ble', 'unit' => 'kg', 'price' => 1.60, 'category' => 'Céréales & farines', 'allergens' => ['gluten']],
            ['name' => 'Tagliatelle', 'slug' => 'tagliatelle', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],
            ['name' => 'Trenette', 'slug' => 'trenette', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Céréales & farines', 'allergens' => []],

            // Produits laitiers
            ['name' => 'Babeurre', 'slug' => 'babeurre', 'unit' => 'L', 'price' => 1.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Beurre', 'slug' => 'beurre', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Beurre clarifié (ghee)', 'slug' => 'beurre-clarifie-ghee', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Beurre doux', 'slug' => 'beurre-doux', 'unit' => 'kg', 'price' => 6.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Burrata', 'slug' => 'burrata', 'unit' => 'kg', 'price' => 24.00, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Camembert', 'slug' => 'camembert', 'unit' => 'pièce', 'price' => 3.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Cheddar', 'slug' => 'cheddar', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Cheddar (sauce)', 'slug' => 'cheddar-sauce', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Chèvre frais', 'slug' => 'chevre-frais', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Comté', 'slug' => 'comte', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème 40%', 'slug' => 'creme-40', 'unit' => 'L', 'price' => 7.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème épaisse allégée', 'slug' => 'creme-epaisse-allegee', 'unit' => 'L', 'price' => 3.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème fraîche épaisse', 'slug' => 'creme-fraiche-epaisse', 'unit' => 'L', 'price' => 3.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Crème liquide entière', 'slug' => 'creme-liquide-entiere', 'unit' => 'L', 'price' => 3.20, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Emmental râpé', 'slug' => 'emmental-rape', 'unit' => 'kg', 'price' => 10.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Feta', 'slug' => 'feta', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Fromage blanc', 'slug' => 'fromage-blanc', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Glace vanille', 'slug' => 'glace-vanille', 'unit' => 'L', 'price' => 6.50, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Gorgonzola', 'slug' => 'gorgonzola', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Grana Padano', 'slug' => 'grana-padano', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Gruyère râpé', 'slug' => 'gruyere-rape', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait concentré non sucré', 'slug' => 'lait-concentre-non-sucre', 'unit' => 'L', 'price' => 2.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait de coco', 'slug' => 'lait-de-coco', 'unit' => 'L', 'price' => 3.50, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Lait demi-écrémé', 'slug' => 'lait-demi-ecreme', 'unit' => 'L', 'price' => 1.05, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait écrémé', 'slug' => 'lait-ecreme', 'unit' => 'L', 'price' => 1.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait entier', 'slug' => 'lait-entier', 'unit' => 'L', 'price' => 1.10, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Lait végétal (soja)', 'slug' => 'lait-vegetal-soja', 'unit' => 'L', 'price' => null, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Manchego', 'slug' => 'manchego', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Mascarpone', 'slug' => 'mascarpone', 'unit' => 'kg', 'price' => 7.50, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Mozzarella', 'slug' => 'mozzarella', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Parmesan', 'slug' => 'parmesan', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Pecorino Romano', 'slug' => 'pecorino-romano', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Produits laitiers', 'allergens' => []],
            ['name' => 'Petit-suisse', 'slug' => 'petit-suisse', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Ricotta', 'slug' => 'ricotta', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Roquefort', 'slug' => 'roquefort', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Produits laitiers', 'allergens' => ['lait']],
            ['name' => 'Yaourt nature', 'slug' => 'yaourt-nature', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Produits laitiers', 'allergens' => ['lait']],

            // Œufs
            ['name' => 'Blanc d\'œuf', 'slug' => 'blanc-doeuf', 'unit' => 'pièce', 'price' => 0.20, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Blancs d\'oeufs liquides', 'slug' => 'blancs-doeufs-liquides', 'unit' => 'L', 'price' => 4.00, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Jaune d\'œuf', 'slug' => 'jaune-doeuf', 'unit' => 'pièce', 'price' => 0.15, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Jaune d\'œuf dur', 'slug' => 'jaune-doeuf-dur', 'unit' => 'pièce', 'price' => 0.15, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Jaunes d\'oeufs liquides', 'slug' => 'jaunes-doeufs-liquides', 'unit' => 'L', 'price' => 5.50, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Oeufs', 'slug' => 'oeufs', 'unit' => 'pièce', 'price' => 0.30, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Oeufs de caille', 'slug' => 'oeufs-de-caille', 'unit' => 'pièce', 'price' => 0.25, 'category' => 'Œufs', 'allergens' => ['oeuf']],
            ['name' => 'Oeufs durs', 'slug' => 'oeufs-durs', 'unit' => 'pièce', 'price' => 0.40, 'category' => 'Œufs', 'allergens' => ['oeuf']],

            // Fruits secs & oléagineux
            ['name' => 'Abricots secs', 'slug' => 'abricots-secs', 'unit' => 'kg', 'price' => 7.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['sulfites']],
            ['name' => 'Amandes effilées', 'slug' => 'amandes-effilees', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Amandes en poudre', 'slug' => 'amandes-en-poudre', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Amandes entières', 'slug' => 'amandes-entieres', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Beurre de cacahuète', 'slug' => 'beurre-de-cacahuete', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['arachides']],
            ['name' => 'Cacahuètes', 'slug' => 'cacahuetes', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['arachides']],
            ['name' => 'Dattes', 'slug' => 'dattes', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Figues sèches', 'slug' => 'figues-seches', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de chia', 'slug' => 'graines-de-chia', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de courge', 'slug' => 'graines-de-courge', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de lin', 'slug' => 'graines-de-lin', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Graines de sésame', 'slug' => 'graines-de-sesame', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['sésame']],
            ['name' => 'Graines de tournesol', 'slug' => 'graines-de-tournesol', 'unit' => 'kg', 'price' => 5.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Noisettes', 'slug' => 'noisettes', 'unit' => 'kg', 'price' => 13.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Noix', 'slug' => 'noix', 'unit' => 'kg', 'price' => 12.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Noix de cajou', 'slug' => 'noix-de-cajou', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Noix de coco râpée', 'slug' => 'noix-de-coco-rapee', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],
            ['name' => 'Pignons de pin', 'slug' => 'pignons-de-pin', 'unit' => 'kg', 'price' => 35.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Pistaches', 'slug' => 'pistaches', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Fruits secs & oléagineux', 'allergens' => ['fruits Coque']],
            ['name' => 'Raisins secs', 'slug' => 'raisins-secs', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Fruits secs & oléagineux', 'allergens' => []],

            // Poissons & fruits de mer
            ['name' => 'Anchois', 'slug' => 'anchois', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Anguille', 'slug' => 'anguille', 'unit' => 'kg', 'price' => 24.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Bar (loup)', 'slug' => 'bar-loup', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Bisque de homard', 'slug' => 'bisque-de-homard', 'unit' => 'L', 'price' => null, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Cabillaud', 'slug' => 'cabillaud', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Calamars', 'slug' => 'calamars', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['mollusques']],
            ['name' => 'Colin (lieu noir)', 'slug' => 'colin-lieu-noir', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Coquilles Saint-Jacques', 'slug' => 'coquilles-saint-jacques', 'unit' => 'kg', 'price' => 30.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['mollusques']],
            ['name' => 'Crabe', 'slug' => 'crabe', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Crevettes', 'slug' => 'crevettes', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Dorade', 'slug' => 'dorade', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Filet d\'anchois', 'slug' => 'filet-danchois', 'unit' => 'pièce', 'price' => 0.20, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Flétan', 'slug' => 'fletan', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Gambas', 'slug' => 'gambas', 'unit' => 'kg', 'price' => 26.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Hareng', 'slug' => 'hareng', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Homard', 'slug' => 'homard', 'unit' => 'kg', 'price' => 45.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Huîtres', 'slug' => 'huitres', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Poissons & fruits de mer', 'allergens' => ['mollusques']],
            ['name' => 'Langoustines', 'slug' => 'langoustines', 'unit' => 'kg', 'price' => 32.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['crustaces']],
            ['name' => 'Maquereau', 'slug' => 'maquereau', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Merlan', 'slug' => 'merlan', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Moules', 'slug' => 'moules', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Poissons & fruits de mer', 'allergens' => ['mollusques']],
            ['name' => 'Palourdes', 'slug' => 'palourdes', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Parures de poisson (arêtes et chutes)', 'slug' => 'parures-de-poisson', 'unit' => 'kg', 'price' => null, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Poulpe', 'slug' => 'poulpe', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Poissons & fruits de mer', 'allergens' => []],
            ['name' => 'Sardine', 'slug' => 'sardine', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Sardines aux piments (boîte)', 'slug' => 'sardines-aux-piments-boite', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Sauce nuoc-mâm (sauce poisson)', 'slug' => 'sauce-nuoc-mam', 'unit' => 'L', 'price' => 9.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Saumon', 'slug' => 'saumon', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Sole', 'slug' => 'sole', 'unit' => 'kg', 'price' => 28.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Thon en boîte', 'slug' => 'thon-en-boite', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Thon frais', 'slug' => 'thon-frais', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],
            ['name' => 'Truite', 'slug' => 'truite', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Poissons & fruits de mer', 'allergens' => ['poisson']],

            // Viandes
            ['name' => 'Agneau haché', 'slug' => 'agneau-hache', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bacon', 'slug' => 'bacon', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bavette de boeuf', 'slug' => 'bavette-de-boeuf', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Biche (viande)', 'slug' => 'biche-viande', 'unit' => 'kg', 'price' => 45.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Blanc de poulet', 'slug' => 'blanc-de-poulet', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Blanquette de veau', 'slug' => 'blanquette-de-veau', 'unit' => 'kg', 'price' => 17.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Boeuf haché', 'slug' => 'boeuf-hache', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Boudin noir', 'slug' => 'boudin-noir', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bouillon de volaille', 'slug' => 'bouillon-de-volaille', 'unit' => 'L', 'price' => 2.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Bresaola', 'slug' => 'bresaola', 'unit' => 'kg', 'price' => 35.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Caille', 'slug' => 'caille', 'unit' => 'pièce', 'price' => 4.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Chorizo', 'slug' => 'chorizo', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Confit de canard', 'slug' => 'confit-de-canard', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Côte de bœuf', 'slug' => 'cote-de-boeuf', 'unit' => 'kg', 'price' => 28.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Côtelettes d\'agneau', 'slug' => 'cotelettes-dagneau', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Côtes de porc', 'slug' => 'cotes-de-porc', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Cuisse de poulet', 'slug' => 'cuisse-de-poulet', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Échine de porc', 'slug' => 'echine-de-porc', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Entrecôte de boeuf', 'slug' => 'entrecote-de-boeuf', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Épaule d\'agneau', 'slug' => 'epaule-dagneau', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Escalope de dinde', 'slug' => 'escalope-de-dinde', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Escalope de veau', 'slug' => 'escalope-de-veau', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Filet de boeuf', 'slug' => 'filet-de-boeuf', 'unit' => 'kg', 'price' => 32.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Filet mignon de porc', 'slug' => 'filet-mignon-de-porc', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Foie gras', 'slug' => 'foie-gras', 'unit' => 'kg', 'price' => 55.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Gigot d\'agneau', 'slug' => 'gigot-dagneau', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Guanciale', 'slug' => 'guanciale', 'unit' => 'kg', 'price' => 24.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Jambon blanc', 'slug' => 'jambon-blanc', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Jambon sec', 'slug' => 'jambon-sec', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Jarret de veau', 'slug' => 'jarret-de-veau', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Joue de boeuf', 'slug' => 'joue-de-boeuf', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Lapin', 'slug' => 'lapin', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Lard fumé', 'slug' => 'lard-fume', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Lardons', 'slug' => 'lardons', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Magret de canard', 'slug' => 'magret-de-canard', 'unit' => 'kg', 'price' => 22.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Mortadelle', 'slug' => 'mortadelle', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Noix de veau', 'slug' => 'noix-de-veau', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Os de veau et de bœuf', 'slug' => 'os-de-veau-et-de-boeuf', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Paleron de boeuf (bourguignon)', 'slug' => 'paleron-de-boeuf-bourguignon', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Pancetta', 'slug' => 'pancetta', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Poulet entier', 'slug' => 'poulet-entier', 'unit' => 'kg', 'price' => 6.50, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rillettes', 'slug' => 'rillettes', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rôti de boeuf', 'slug' => 'roti-de-boeuf', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Rôti de veau', 'slug' => 'roti-de-veau', 'unit' => 'kg', 'price' => 19.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Saucisse italienne', 'slug' => 'saucisse-italienne', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Saucisses de Toulouse', 'slug' => 'saucisses-de-toulouse', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Viandes', 'allergens' => []],
            ['name' => 'Saucisson sec', 'slug' => 'saucisson-sec', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Viandes', 'allergens' => []],

            // Légumes
            ['name' => 'Ail', 'slug' => 'ail', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Aneth', 'slug' => 'aneth', 'unit' => 'bouquet', 'price' => 2.75, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Artichaut', 'slug' => 'artichaut', 'unit' => 'pièce', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Asperge verte', 'slug' => 'asperge-verte', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Aubergine', 'slug' => 'aubergine', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Basilic', 'slug' => 'basilic', 'unit' => 'botte', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Basilic thaï', 'slug' => 'basilic-thai', 'unit' => 'botte', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Betterave', 'slug' => 'betterave', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Bouillon de légumes', 'slug' => 'bouillon-de-legumes', 'unit' => 'L', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Brocoli', 'slug' => 'brocoli', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Carotte', 'slug' => 'carotte', 'unit' => 'kg', 'price' => 1.10, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Céleri branche', 'slug' => 'celeri-branche', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Légumes', 'allergens' => ['celeri']],
            ['name' => 'Céleri-rave', 'slug' => 'celeri-rave', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => ['celeri']],
            ['name' => 'Cèpes', 'slug' => 'cepes', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Champignon de Paris', 'slug' => 'champignon-de-paris', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou blanc', 'slug' => 'chou-blanc', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou de Bruxelles', 'slug' => 'chou-de-bruxelles', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou rouge', 'slug' => 'chou-rouge', 'unit' => 'kg', 'price' => 1.70, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Chou-fleur', 'slug' => 'chou-fleur', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Ciboule chinoise (ciboulette ail)', 'slug' => 'ciboule-chinoise', 'unit' => 'kg', 'price' => 18.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Ciboulette', 'slug' => 'ciboulette', 'unit' => 'botte', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Ciboulette hachée', 'slug' => 'ciboulette-hachee', 'unit' => 'c. à soupe', 'price' => 0.15, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Concombre', 'slug' => 'concombre', 'unit' => 'pièce', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Coriandre fraîche', 'slug' => 'coriandre-fraiche', 'unit' => 'botte', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Coulis de tomate (boîte)', 'slug' => 'coulis-de-tomate-boite', 'unit' => 'boîte', 'price' => 1.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Courge butternut', 'slug' => 'courge-butternut', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Courgette', 'slug' => 'courgette', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Échalote', 'slug' => 'echalote', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Endive', 'slug' => 'endive', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Épinard', 'slug' => 'epinard', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Fenouil', 'slug' => 'fenouil', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Fève', 'slug' => 'feve', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Gingembre frais', 'slug' => 'gingembre-frais', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Girolles', 'slug' => 'girolles', 'unit' => 'kg', 'price' => 25.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Gousse d\'ail', 'slug' => 'gousse-dail', 'unit' => 'gousse', 'price' => 0.03, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Haricot vert', 'slug' => 'haricot-vert', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Haricots noirs', 'slug' => 'haricots-noirs', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Jalapeños', 'slug' => 'jalapenos', 'unit' => 'pièce', 'price' => 0.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Mâche', 'slug' => 'mache', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Maïs doux', 'slug' => 'mais-doux', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Navet', 'slug' => 'navet', 'unit' => 'kg', 'price' => 1.60, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Oignon', 'slug' => 'oignon', 'unit' => 'kg', 'price' => 1.30, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Oignon grelot', 'slug' => 'oignon-grelot', 'unit' => 'kg', 'price' => 3.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Persil', 'slug' => 'persil', 'unit' => 'botte', 'price' => 1.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Petit pois', 'slug' => 'petit-pois', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Piment fort', 'slug' => 'piment-fort', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Pleurotes', 'slug' => 'pleurotes', 'unit' => 'kg', 'price' => null, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poireau', 'slug' => 'poireau', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poivron rouge', 'slug' => 'poivron-rouge', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Poivron vert', 'slug' => 'poivron-vert', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Pomme de terre', 'slug' => 'pomme-de-terre', 'unit' => 'kg', 'price' => 1.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Potiron', 'slug' => 'potiron', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Pousses de soja', 'slug' => 'pousses-de-soja', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Légumes', 'allergens' => ['soja']],
            ['name' => 'Radis', 'slug' => 'radis', 'unit' => 'botte', 'price' => 1.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Romarin frais', 'slug' => 'romarin-frais', 'unit' => 'branche', 'price' => 0.10, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Roquette', 'slug' => 'roquette', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Salade verte', 'slug' => 'salade-verte', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Sauge', 'slug' => 'sauge', 'unit' => 'botte', 'price' => 2.00, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Tomate', 'slug' => 'tomate', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Légumes', 'allergens' => []],
            ['name' => 'Tomates séchées', 'slug' => 'tomates-sechees', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Légumes', 'allergens' => []],

            // Fruits
            ['name' => 'Abricot', 'slug' => 'abricot', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Ananas', 'slug' => 'ananas', 'unit' => 'pièce', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Banane', 'slug' => 'banane', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Cerise', 'slug' => 'cerise', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Citron', 'slug' => 'citron', 'unit' => 'kg', 'price' => 2.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Citron vert', 'slug' => 'citron-vert', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Figue fraîche', 'slug' => 'figue-fraiche', 'unit' => 'kg', 'price' => 7.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Fraise', 'slug' => 'fraise', 'unit' => 'kg', 'price' => 6.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Framboise', 'slug' => 'framboise', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Fruit de la passion', 'slug' => 'fruit-de-la-passion', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Grenade', 'slug' => 'grenade', 'unit' => 'pièce', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Jus de citron', 'slug' => 'jus-de-citron', 'unit' => 'g', 'price' => 0.01, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Jus de citron vert', 'slug' => 'jus-de-citron-vert', 'unit' => 'g', 'price' => 0.01, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Kiwi', 'slug' => 'kiwi', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Litchi', 'slug' => 'litchi', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mandarine', 'slug' => 'mandarine', 'unit' => 'kg', 'price' => 2.60, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mangue', 'slug' => 'mangue', 'unit' => 'pièce', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Melon', 'slug' => 'melon', 'unit' => 'pièce', 'price' => 2.80, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Mûre', 'slug' => 'mure', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Myrtille', 'slug' => 'myrtille', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Nectarine', 'slug' => 'nectarine', 'unit' => 'kg', 'price' => 3.60, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Orange', 'slug' => 'orange', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pamplemousse', 'slug' => 'pamplemousse', 'unit' => 'kg', 'price' => 2.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Papaye', 'slug' => 'papaye', 'unit' => 'pièce', 'price' => 3.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pastèque', 'slug' => 'pasteque', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pêche', 'slug' => 'peche', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Poire', 'slug' => 'poire', 'unit' => 'kg', 'price' => 2.50, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Pomme', 'slug' => 'pomme', 'unit' => 'kg', 'price' => 2.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Prune', 'slug' => 'prune', 'unit' => 'kg', 'price' => 3.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Raisin blanc', 'slug' => 'raisin-blanc', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Raisin noir', 'slug' => 'raisin-noir', 'unit' => 'kg', 'price' => 4.20, 'category' => 'Fruits', 'allergens' => []],
            ['name' => 'Rhubarbe', 'slug' => 'rhubarbe', 'unit' => 'kg', 'price' => 3.80, 'category' => 'Fruits', 'allergens' => []],

            // Condiments & épices
            ['name' => 'Ail moulu', 'slug' => 'ail-moulu', 'unit' => 'c. à café', 'price' => 0.05, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Baie rose', 'slug' => 'baie-rose', 'unit' => 'c. à café', 'price' => 0.05, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Baies de piment de la Jamaïque', 'slug' => 'baies-piment-jamaique', 'unit' => 'grain', 'price' => 0.02, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Bouquet garni', 'slug' => 'bouquet-garni', 'unit' => 'pièce', 'price' => 1.20, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cacao en poudre', 'slug' => 'cacao-en-poudre', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cannelle', 'slug' => 'cannelle', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Câpres', 'slug' => 'capres', 'unit' => 'g', 'price' => 0.04, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cassonade', 'slug' => 'cassonade', 'unit' => 'kg', 'price' => 1.80, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Chocolat noir 70%', 'slug' => 'chocolat-noir-70', 'unit' => 'kg', 'price' => 30.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cinq épices chinoises', 'slug' => 'cinq-epices-chinoises', 'unit' => 'c. à café', 'price' => 0.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Clou de girofle', 'slug' => 'clou-de-girofle', 'unit' => 'clou', 'price' => 0.02, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Concentré de tomate', 'slug' => 'concentre-de-tomate', 'unit' => 'kg', 'price' => 3.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Coriandre en poudre', 'slug' => 'coriandre-en-poudre', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Cumin', 'slug' => 'cumin', 'unit' => 'kg', 'price' => 11.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Curcuma', 'slug' => 'curcuma', 'unit' => 'kg', 'price' => 10.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Curry', 'slug' => 'curry', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Extrait de café', 'slug' => 'extrait-de-cafe', 'unit' => 'c. à soupe', 'price' => 0.20, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Graines de coriandre', 'slug' => 'graines-de-coriandre', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Graines de fenouil', 'slug' => 'graines-de-fenouil', 'unit' => 'kg', 'price' => 13.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Gros sel', 'slug' => 'gros-sel', 'unit' => 'kg', 'price' => 2.90, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Herbes de Provence', 'slug' => 'herbes-de-provence', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile d\'olive', 'slug' => 'huile-dolive', 'unit' => 'L', 'price' => 7.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile de colza', 'slug' => 'huile-de-colza', 'unit' => 'L', 'price' => 3.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile de friture', 'slug' => 'huile-de-friture', 'unit' => 'L', 'price' => 4.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Huile de sésame', 'slug' => 'huile-de-sesame', 'unit' => 'L', 'price' => 18.00, 'category' => 'Condiments & épices', 'allergens' => ['sésame']],
            ['name' => 'Huile de tournesol', 'slug' => 'huile-de-tournesol', 'unit' => 'L', 'price' => 2.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Ketchup', 'slug' => 'ketchup', 'unit' => 'kg', 'price' => 3.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Laurier', 'slug' => 'laurier', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Laurier (feuille)', 'slug' => 'laurier-feuille', 'unit' => 'feuille', 'price' => 0.02, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Mayonnaise', 'slug' => 'mayonnaise', 'unit' => 'kg', 'price' => 4.50, 'category' => 'Condiments & épices', 'allergens' => ['oeuf']],
            ['name' => 'Miel', 'slug' => 'miel', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Moutarde de Dijon', 'slug' => 'moutarde-de-dijon', 'unit' => 'kg', 'price' => 4.00, 'category' => 'Condiments & épices', 'allergens' => ['moutarde']],
            ['name' => 'Muscade', 'slug' => 'muscade', 'unit' => 'kg', 'price' => 20.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Oignon en poudre', 'slug' => 'oignon-en-poudre', 'unit' => 'c. à café', 'price' => 0.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Oignons frits croustillants', 'slug' => 'oignons-frits-croustillants', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Olives vertes', 'slug' => 'olives-vertes', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Origan', 'slug' => 'origan', 'unit' => 'kg', 'price' => 8.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Pappardelle fraîches', 'slug' => 'pappardelle-fraiches', 'unit' => 'kg', 'price' => 9.00, 'category' => 'Condiments & épices', 'allergens' => ['gluten', 'oeuf']],
            ['name' => 'Paprika', 'slug' => 'paprika', 'unit' => 'kg', 'price' => 12.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Paprika fumé', 'slug' => 'paprika-fume', 'unit' => 'c. à café', 'price' => 0.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Pâte de curry rouge thaï', 'slug' => 'pate-de-curry-rouge-thai', 'unit' => 'kg', 'price' => 14.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Pâte de tamarin', 'slug' => 'pate-de-tamarin', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Pili pili', 'slug' => 'pili-pili', 'unit' => 'gr', 'price' => 0.05, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Piment d\'Espelette', 'slug' => 'piment-despelette', 'unit' => 'kg', 'price' => 30.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre blanc', 'slug' => 'poivre-blanc', 'unit' => 'kg', 'price' => 16.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre noir', 'slug' => 'poivre-noir', 'unit' => 'kg', 'price' => 15.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre noir en grains', 'slug' => 'poivre-noir-en-grains', 'unit' => 'grain', 'price' => 0.01, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre noir moulu', 'slug' => 'poivre-noir-moulu', 'unit' => 'c. à café', 'price' => 0.05, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Poivre vert granulé', 'slug' => 'poivre-vert-granule', 'unit' => 'g', 'price' => 0.05, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Proespuma Frio', 'slug' => 'proespuma-frio', 'unit' => 'g', 'price' => null, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Quatre-épices', 'slug' => 'quatre-epices', 'unit' => 'kg', 'price' => null, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Romarin', 'slug' => 'romarin', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Safran (dose)', 'slug' => 'safran-dose', 'unit' => 'dose', 'price' => 10.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sauce soja', 'slug' => 'sauce-soja', 'unit' => 'L', 'price' => 3.20, 'category' => 'Condiments & épices', 'allergens' => ['gluten', 'soja']],
            ['name' => 'Sauce sriracha', 'slug' => 'sauce-sriracha', 'unit' => 'L', 'price' => 7.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sauce Worcestershire', 'slug' => 'sauce-worcestershire', 'unit' => 'L', 'price' => 8.00, 'category' => 'Condiments & épices', 'allergens' => ['poisson']],
            ['name' => 'Sel fin', 'slug' => 'sel-fin', 'unit' => 'kg', 'price' => 0.80, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sucre blanc', 'slug' => 'sucre-blanc', 'unit' => 'kg', 'price' => 1.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sucre de palme', 'slug' => 'sucre-de-palme', 'unit' => 'kg', 'price' => 8.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Sucre roux', 'slug' => 'sucre-roux', 'unit' => 'kg', 'price' => 1.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Thym', 'slug' => 'thym', 'unit' => 'kg', 'price' => 9.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Thym (branche)', 'slug' => 'thym-branche', 'unit' => 'branche', 'price' => 0.10, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Tofu ferme', 'slug' => 'tofu-ferme', 'unit' => 'kg', 'price' => 5.50, 'category' => 'Condiments & épices', 'allergens' => ['soja']],
            ['name' => 'Vanille (gousse)', 'slug' => 'vanille-gousse', 'unit' => 'pièce', 'price' => 3.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre balsamique', 'slug' => 'vinaigre-balsamique', 'unit' => 'L', 'price' => 6.00, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre de cidre', 'slug' => 'vinaigre-de-cidre', 'unit' => 'L', 'price' => 3.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre de riz', 'slug' => 'vinaigre-de-riz', 'unit' => 'L', 'price' => 5.50, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre de vin blanc', 'slug' => 'vinaigre-de-vin-blanc', 'unit' => 'L', 'price' => null, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Vinaigre de vin rouge', 'slug' => 'vinaigre-de-vin-rouge', 'unit' => 'L', 'price' => null, 'category' => 'Condiments & épices', 'allergens' => []],
            ['name' => 'Zeste de citron jaune', 'slug' => 'zeste-de-citron-jaune', 'unit' => 'pièce', 'price' => 2.15, 'category' => 'Condiments & épices', 'allergens' => []],

            // Boissons & vins
            ['name' => 'Amaretto', 'slug' => 'amaretto', 'unit' => 'L', 'price' => 26.00, 'category' => 'Boissons & vins', 'allergens' => ['fruits Coque']],
            ['name' => 'Bière blonde', 'slug' => 'biere-blonde', 'unit' => 'L', 'price' => 2.50, 'category' => 'Boissons & vins', 'allergens' => ['gluten']],
            ['name' => 'Café expresso (préparé)', 'slug' => 'cafe-expresso-prepare', 'unit' => 'L', 'price' => 2.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Champagne', 'slug' => 'champagne', 'unit' => 'L', 'price' => 25.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Cidre brut', 'slug' => 'cidre-brut', 'unit' => 'L', 'price' => 3.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Cognac', 'slug' => 'cognac', 'unit' => 'L', 'price' => 30.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Gin sec', 'slug' => 'gin-sec', 'unit' => 'L', 'price' => 62.50, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Jus de pomme', 'slug' => 'jus-de-pomme', 'unit' => 'L', 'price' => 2.20, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Porto', 'slug' => 'porto', 'unit' => 'L', 'price' => 12.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Prosecco', 'slug' => 'prosecco', 'unit' => 'L', 'price' => 12.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Rhum brun', 'slug' => 'rhum-brun', 'unit' => 'L', 'price' => 18.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Vin blanc', 'slug' => 'vin-blanc', 'unit' => 'L', 'price' => 5.00, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Vin de riz Shaoxing', 'slug' => 'vin-de-riz-shaoxing', 'unit' => 'L', 'price' => 9.00, 'category' => 'Boissons & vins', 'allergens' => []],
            ['name' => 'Vin rosé', 'slug' => 'vin-rose', 'unit' => 'L', 'price' => 5.20, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],
            ['name' => 'Vin rouge', 'slug' => 'vin-rouge', 'unit' => 'L', 'price' => 5.50, 'category' => 'Boissons & vins', 'allergens' => ['sulfites']],

            // Sans catégorie (pas encore classés dans le dashboard)
            ['name' => 'Agar-agar', 'slug' => 'agar-agar', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Armagnac', 'slug' => 'armagnac', 'unit' => 'L', 'price' => 60.00, 'category' => null, 'allergens' => []],
            ['name' => 'Avocat', 'slug' => 'avocat', 'unit' => 'pièce', 'price' => 1.50, 'category' => null, 'allergens' => []],
            ['name' => 'Baccalà (morue salée dessalée, cuite)', 'slug' => 'baccala-morue-salee-dessalee-cuite', 'unit' => 'kg', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Beurre doux, à température ambiante', 'slug' => 'beurre-doux-a-temperature-ambiante', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Beurre, huile', 'slug' => 'beurre-huile', 'unit' => 'QS', 'price' => null, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Bière brune', 'slug' => 'biere-brune', 'unit' => 'L', 'price' => 4.00, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Bouillon de bœuf', 'slug' => 'bouillon-de-boeuf', 'unit' => 'L', 'price' => 2.50, 'category' => null, 'allergens' => []],
            ['name' => 'Carotte fane', 'slug' => 'carotte-fane', 'unit' => 'botte', 'price' => 2.00, 'category' => null, 'allergens' => []],
            ['name' => 'Cartouches pour siphon', 'slug' => 'cartouches-pour-siphon', 'unit' => 'pièce', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Cerfeuil', 'slug' => 'cerfeuil', 'unit' => 'botte', 'price' => 2.00, 'category' => null, 'allergens' => []],
            ['name' => 'Champignons forestiers (girolles, chanterelles grises, trompettes...)', 'slug' => 'champignons-forestiers-girolles-chanterelles-grises-trompettes', 'unit' => 'kg', 'price' => 28.00, 'category' => null, 'allergens' => []],
            ['name' => 'Châtaignes cuites', 'slug' => 'chataignes-cuites', 'unit' => 'kg', 'price' => 9.00, 'category' => null, 'allergens' => []],
            ['name' => 'Chocolat blanc', 'slug' => 'chocolat-blanc', 'unit' => 'kg', 'price' => 25.00, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Confiture de framboise', 'slug' => 'confiture-de-framboise', 'unit' => 'kg', 'price' => 9.00, 'category' => null, 'allergens' => []],
            ['name' => 'Confiture de pêche', 'slug' => 'confiture-de-peche', 'unit' => 'kg', 'price' => 8.50, 'category' => null, 'allergens' => []],
            ['name' => 'Cornichons', 'slug' => 'cornichons', 'unit' => 'g', 'price' => 0.02, 'category' => null, 'allergens' => []],
            ['name' => 'Couenne de porc', 'slug' => 'couenne-de-porc', 'unit' => 'kg', 'price' => 4.00, 'category' => null, 'allergens' => []],
            ['name' => 'Crème fraîche épaisse bio', 'slug' => 'creme-fraiche-epaisse-bio', 'unit' => 'c. à soupe', 'price' => 0.12, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Crème liquide', 'slug' => 'creme-liquide', 'unit' => 'L', 'price' => 4.50, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Crosnes', 'slug' => 'crosnes', 'unit' => 'kg', 'price' => 18.00, 'category' => null, 'allergens' => []],
            ['name' => 'Eau', 'slug' => 'eau', 'unit' => 'L', 'price' => 0.01, 'category' => null, 'allergens' => []],
            ['name' => 'Estragon', 'slug' => 'estragon', 'unit' => 'g', 'price' => 0.13, 'category' => null, 'allergens' => []],
            ['name' => 'Farine', 'slug' => 'farine', 'unit' => 'kg', 'price' => 1.10, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Farine de pain', 'slug' => 'farine-de-pain', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Filet de volaille fermière Label Rouge (Gers)', 'slug' => 'filet-de-volaille-fermiere-label-rouge-gers', 'unit' => 'pièce', 'price' => 4.50, 'category' => null, 'allergens' => []],
            ['name' => 'Foies de volaille', 'slug' => 'foies-de-volaille', 'unit' => 'kg', 'price' => 8.00, 'category' => null, 'allergens' => []],
            ['name' => 'Fond de volaille', 'slug' => 'fond-de-volaille', 'unit' => 'L', 'price' => 6.00, 'category' => null, 'allergens' => []],
            ['name' => 'Fond de volaille bio', 'slug' => 'fond-de-volaille-bio', 'unit' => 'L', 'price' => 7.50, 'category' => null, 'allergens' => []],
            ['name' => 'Fromage frais (type St Môret)', 'slug' => 'fromage-frais-type-st-moret', 'unit' => 'kg', 'price' => 6.50, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Gélatine', 'slug' => 'gelatine', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Gîte de bœuf', 'slug' => 'gite-de-boeuf', 'unit' => 'kg', 'price' => 18.00, 'category' => null, 'allergens' => []],
            ['name' => 'Gomme xanthane', 'slug' => 'gomme-xanthane', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Gorge de porc', 'slug' => 'gorge-de-porc', 'unit' => 'kg', 'price' => 8.00, 'category' => null, 'allergens' => []],
            ['name' => 'Graisse de canard', 'slug' => 'graisse-de-canard', 'unit' => 'kg', 'price' => 9.00, 'category' => null, 'allergens' => []],
            ['name' => 'Grand Marnier', 'slug' => 'grand-marnier', 'unit' => 'L', 'price' => 35.00, 'category' => null, 'allergens' => []],
            ['name' => 'Haricots blancs secs (lingots)', 'slug' => 'haricots-blancs-secs-lingots', 'unit' => 'kg', 'price' => 5.00, 'category' => null, 'allergens' => []],
            ['name' => 'Huile', 'slug' => 'huile', 'unit' => 'trait', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Huile de coco', 'slug' => 'huile-de-coco', 'unit' => 'L', 'price' => 10.00, 'category' => null, 'allergens' => []],
            ['name' => 'Jambon cru', 'slug' => 'jambon-cru', 'unit' => 'kg', 'price' => 30.00, 'category' => null, 'allergens' => []],
            ['name' => 'Jus de pamplemousse', 'slug' => 'jus-de-pamplemousse', 'unit' => 'L', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Kiri (fromage à tartiner)', 'slug' => 'kiri-fromage-a-tartiner', 'unit' => 'pièce', 'price' => 0.15, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Lait', 'slug' => 'lait', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Levure instantanée', 'slug' => 'levure-instantanee', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Macreuse de bœuf', 'slug' => 'macreuse-de-boeuf', 'unit' => 'kg', 'price' => 20.00, 'category' => null, 'allergens' => []],
            ['name' => 'Madère', 'slug' => 'madere', 'unit' => 'L', 'price' => 12.00, 'category' => null, 'allergens' => ['sulfites']],
            ['name' => 'Menthe fraîche', 'slug' => 'menthe-fraiche', 'unit' => 'botte', 'price' => 2.00, 'category' => null, 'allergens' => []],
            ['name' => 'Mimolette', 'slug' => 'mimolette', 'unit' => 'kg', 'price' => 35.00, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Mini-poireau', 'slug' => 'mini-poireau', 'unit' => 'pièce', 'price' => 0.90, 'category' => null, 'allergens' => []],
            ['name' => 'Morilles', 'slug' => 'morilles', 'unit' => 'kg', 'price' => 100.00, 'category' => null, 'allergens' => []],
            ['name' => 'Moutarde à l\'ancienne', 'slug' => 'moutarde-a-l-ancienne', 'unit' => 'kg', 'price' => 7.00, 'category' => null, 'allergens' => ['moutarde']],
            ['name' => 'Nori (feuilles)', 'slug' => 'nori-feuilles', 'unit' => 'pièce', 'price' => 0.30, 'category' => null, 'allergens' => []],
            ['name' => 'Œuf (environ 50 g sans coquille)', 'slug' => 'uf-environ-50-g-sans-coquille', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Oignon rouge', 'slug' => 'oignon-rouge', 'unit' => 'kg', 'price' => 2.80, 'category' => null, 'allergens' => []],
            ['name' => 'Oignon rouge mariné', 'slug' => 'oignon-rouge-marine', 'unit' => 'kg', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Olives noires', 'slug' => 'olives-noires', 'unit' => 'kg', 'price' => 9.00, 'category' => null, 'allergens' => []],
            ['name' => 'Os à moelle', 'slug' => 'os-a-moelle', 'unit' => 'pièce', 'price' => 5.00, 'category' => null, 'allergens' => []],
            ['name' => 'Pain bagel', 'slug' => 'pain-bagel', 'unit' => 'pièce', 'price' => 1.00, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Pain d\'épices', 'slug' => 'pain-d-epices', 'unit' => 'kg', 'price' => 11.00, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Pain de campagne', 'slug' => 'pain-de-campagne', 'unit' => 'kg', 'price' => 4.50, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Pak choï', 'slug' => 'pak-choi', 'unit' => 'kg', 'price' => 5.00, 'category' => null, 'allergens' => []],
            ['name' => 'Patate douce', 'slug' => 'patate-douce', 'unit' => 'kg', 'price' => 2.80, 'category' => null, 'allergens' => []],
            ['name' => 'Pâte de praliné', 'slug' => 'pate-de-praline', 'unit' => 'kg', 'price' => 20.00, 'category' => null, 'allergens' => ['fruits Coque']],
            ['name' => 'Pâte feuilletée', 'slug' => 'pate-feuilletee', 'unit' => 'kg', 'price' => 5.50, 'category' => null, 'allergens' => ['gluten', 'lait']],
            ['name' => 'Pâte miso', 'slug' => 'pate-miso', 'unit' => 'kg', 'price' => 16.00, 'category' => null, 'allergens' => ['soja']],
            ['name' => 'Perles de blé', 'slug' => 'perles-de-ble', 'unit' => 'kg', 'price' => 3.00, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Petits pains navettes', 'slug' => 'petits-pains-navettes', 'unit' => 'pièce', 'price' => 0.50, 'category' => null, 'allergens' => ['gluten']],
            ['name' => 'Pigeon', 'slug' => 'pigeon', 'unit' => 'pièce', 'price' => 14.00, 'category' => null, 'allergens' => []],
            ['name' => 'Pois cassés', 'slug' => 'pois-casses', 'unit' => 'kg', 'price' => 2.60, 'category' => null, 'allergens' => []],
            ['name' => 'Pois chiches', 'slug' => 'pois-chiches', 'unit' => 'kg', 'price' => 2.80, 'category' => null, 'allergens' => []],
            ['name' => 'Poitrine de porc', 'slug' => 'poitrine-de-porc', 'unit' => 'kg', 'price' => 10.00, 'category' => null, 'allergens' => []],
            ['name' => 'Pommes de terre fermes', 'slug' => 'pommes-de-terre-fermes', 'unit' => 'kg', 'price' => 1.80, 'category' => null, 'allergens' => []],
            ['name' => 'Potimarron', 'slug' => 'potimarron', 'unit' => 'kg', 'price' => 2.50, 'category' => null, 'allergens' => []],
            ['name' => 'Reblochon', 'slug' => 'reblochon', 'unit' => 'pièce', 'price' => 16.00, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Ris de veau', 'slug' => 'ris-de-veau', 'unit' => 'kg', 'price' => 45.00, 'category' => null, 'allergens' => []],
            ['name' => 'Salade romaine', 'slug' => 'salade-romaine', 'unit' => 'pièce', 'price' => 1.30, 'category' => null, 'allergens' => []],
            ['name' => 'Sardines à l\'huile d\'olive (boîte)', 'slug' => 'sardines-a-l-huile-d-olive-boite', 'unit' => 'kg', 'price' => 18.00, 'category' => null, 'allergens' => ['poisson']],
            ['name' => 'Sauce barbecue', 'slug' => 'sauce-barbecue', 'unit' => 'kg', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Sel', 'slug' => 'sel', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Sel, poivre', 'slug' => 'sel-poivre', 'unit' => 'QS', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Sel, poivre de Madagascar', 'slug' => 'sel-poivre-de-madagascar', 'unit' => 'QS', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Shitaké', 'slug' => 'shitake', 'unit' => 'kg', 'price' => 18.00, 'category' => null, 'allergens' => []],
            ['name' => 'Sirop d\'érable', 'slug' => 'sirop-d-erable', 'unit' => 'L', 'price' => 28.00, 'category' => null, 'allergens' => []],
            ['name' => 'Sirop de gingembre', 'slug' => 'sirop-de-gingembre', 'unit' => 'L', 'price' => 9.00, 'category' => null, 'allergens' => []],
            ['name' => 'Sirop de Liège', 'slug' => 'sirop-de-liege', 'unit' => 'L', 'price' => 11.00, 'category' => null, 'allergens' => []],
            ['name' => 'Skyr', 'slug' => 'skyr', 'unit' => 'kg', 'price' => 4.50, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Sucre', 'slug' => 'sucre', 'unit' => 'g', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Sucre glace', 'slug' => 'sucre-glace', 'unit' => 'kg', 'price' => 1.80, 'category' => null, 'allergens' => []],
            ['name' => 'Surimi', 'slug' => 'surimi', 'unit' => 'kg', 'price' => 9.00, 'category' => null, 'allergens' => ['poisson']],
            ['name' => 'Tabasco', 'slug' => 'tabasco', 'unit' => 'L', 'price' => 40.00, 'category' => null, 'allergens' => []],
            ['name' => 'Topinambour', 'slug' => 'topinambour', 'unit' => 'kg', 'price' => 4.50, 'category' => null, 'allergens' => []],
            ['name' => 'Tranche de brioche', 'slug' => 'tranche-de-brioche', 'unit' => 'pièce', 'price' => 0.30, 'category' => null, 'allergens' => ['gluten', 'lait', 'oeuf']],
            ['name' => 'Travers de porc (ribs)', 'slug' => 'travers-de-porc-ribs', 'unit' => 'kg', 'price' => null, 'category' => null, 'allergens' => []],
            ['name' => 'Truffe', 'slug' => 'truffe', 'unit' => 'kg', 'price' => 900.00, 'category' => null, 'allergens' => []],
            ['name' => 'Turbot', 'slug' => 'turbot', 'unit' => 'kg', 'price' => 40.00, 'category' => null, 'allergens' => []],
            ['name' => 'Vergeoise', 'slug' => 'vergeoise', 'unit' => 'kg', 'price' => 2.20, 'category' => null, 'allergens' => []],
            ['name' => 'Vin jaune', 'slug' => 'vin-jaune', 'unit' => 'L', 'price' => 95.00, 'category' => null, 'allergens' => ['sulfites']],
            ['name' => 'Vinaigre d\'alcool blanc', 'slug' => 'vinaigre-alcool-blanc', 'unit' => 'L', 'price' => 1.20, 'category' => null, 'allergens' => []],
            ['name' => 'Vinaigre de framboise', 'slug' => 'vinaigre-de-framboise', 'unit' => 'L', 'price' => 11.00, 'category' => null, 'allergens' => []],
            ['name' => 'Vinaigre de Melfor', 'slug' => 'vinaigre-de-melfor', 'unit' => 'L', 'price' => 7.00, 'category' => null, 'allergens' => []],
            ['name' => 'Wasabi', 'slug' => 'wasabi', 'unit' => 'kg', 'price' => 320.00, 'category' => null, 'allergens' => []],
            ['name' => 'Yaourt grec', 'slug' => 'yaourt-grec', 'unit' => 'kg', 'price' => 4.50, 'category' => null, 'allergens' => ['lait']],
            ['name' => 'Zeste de pamplemousse', 'slug' => 'zeste-de-pamplemousse', 'unit' => 'pièce', 'price' => null, 'category' => null, 'allergens' => []],

        ];
        foreach ($ingredients as $data) {
            $categoryId = $data['category']
                ? IngredientCategory::where('slug', Str::slug($data['category']))->value('id')
                : null;

            // On matche sur le slug exact stocké en base plutôt que de le recalculer via
            // Str::slug($data['name']) : le dashboard (Angular) calcule son propre slug à la
            // création d'un ingrédient, avec un algorithme qui ne traite pas toujours les
            // apostrophes/accents exactement comme Str::slug() côté PHP (ex. "Vinaigre d'alcool
            // blanc" -> "vinaigre-alcool-blanc" côté dashboard vs "vinaigre-dalcool-blanc" avec
            // Str::slug()) — recalculer créait des doublons au lieu de retrouver l'existant.
            $ingredient = Ingredient::firstOrCreate(
                ['slug' => $data['slug']],
                [
                    'name' => $data['name'],
                    'unit' => $data['unit'],
                    'price' => $data['price'],
                    'ingredient_category_id' => $categoryId,
                ]
            );

            $ingredient->update(['ingredient_category_id' => $categoryId]);

            $allergenIds = Allergen::whereIn('slug', array_map(fn ($name) => Str::slug($name), $data['allergens']))
                ->pluck('id');

            $ingredient->allergens()->sync($allergenIds);
        }
    }
}
